### ISSUE TITLE
Spring Cloud 之 gateway的简单搭建

### ISSUE THREAD

**Issue by Aeizzz** [Aeizzz/aeizzz#6]
## 介绍
服务网关是微服务架构中一个不可或缺的部分。通过服务网关统一向外系统提供REST API的过程中，除了具备服务路由、均衡负载功能之外，它还具备了权限控制等功能。Spring Cloud Netflix中的Zuul就担任了这样的一个角色，为微服务架构提供了前门保护的作用，同时将权限控制这些较重的非业务逻辑内容迁移到服务路由层面，使得服务集群主体能够具备更高的可复用性和可测试性。

## 搭建 gateway
首先加入依赖
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-zuul</artifactId>
</dependency>
```
在主类上添加`@EnableZuulProxy` 注解  
在配置文件中配置转发策略
```
server:
  port: 8010  
zuul:
  ignoredServices: '*'           #除了routes中配置的服务，不代理其它所有服务。
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    admin:
      path: /admin/** #路径匹配规则
      serviceId: admin  #服务ID
      stripPrefix: true #代理时，是否去掉前缀
      sensitiveHeaders:  #敏感头配置（不向下游传播）
```
这样我们请求 `http://localhost:8010/admin/**`  的时候就会转发到 admin 服务下的`/**` 路径

---
更多用法详见文档[路由器和过滤器：Zuul](https://springcloud.cc/spring-cloud-dalston.html#_router_and_filter_zuul)
